### ISSUE TITLE
Understand what the Skyrme Mean Field Potentials Should Be

### ISSUE THREAD

**Issue by lroberts36** [ermalrrapaj/two_phase_skyrme#5]
![image](https://cloud.githubusercontent.com/assets/13839591/9447490/811c720e-4a4c-11e5-8e63-c9abe6672fda.png)
This is a result from the paper:

http://journals.aps.org.oca.ucsc.edu/prc/abstract/10.1103/PhysRevC.5.626

It seems to suggest that the mean field potentials derived from the single particle energies in the Hartree-Fock approximation should include tau dependent pieces.  I have not read the paper in detail yet, so maybe there is something that I am missing.

**Comment by ermalrrapaj** [comment]
Just finished reading the paper, and now it makes more sense - The results are right!
Equation 20 is derived from the taking the functional derivative of the energy density with respect to the single particle wave-function. Both tau and rho are functional of it, thus the 'double' dependence of both effective mean field potential and effective mass. This means that the expressions in the paper from Arnau are not right.

**Comment by ermalrrapaj** [comment]
However, for the specific interactions we are using, the difference is very small as the ratio of effective mass over real mass is almost one.

**Comment by lroberts36** [comment]
Ok, so you agree the k independent portion of the potential should have a tau dependent piece and the Lattimer & Swesty results are correct?

**Comment by ermalrrapaj** [comment]
YES,
The only worry I would have is that U HAS NO K DEPENDENCE at all. If the Schrodinger equation is Fourier transformed into momentum space, the potential acts only as e mean field shift (there are no gradient terms in U) - but this is fine since we are dealing with spatially uniform matter and density or kinetic density gradient terms vanish - these terms would make U have k dependence. While in the other paper U has k dependence and from eq 22(a) adapted for uniform matter that can not happen.
